import { Headings } from "@/components/headings";
export const teamGroupList = [
  // "Baseball Big League",
  "Baseball Adult A Grade",
  "Baseball Adult B Grade",
  "Baseball Adult C Grade",
  "Baseball Adult D Grade",
  "Baseball Adult E Grade",
  "Baseball Adult G Grade",
  "Baseball IL - Green",
  // "Baseball IL - Green (Coach)",
  "Baseball IL - White",
  // "Baseball Intermediate League",
  "Baseball JL - Green",
  "Baseball JL - White",
  // "Baseball Junior League",
  "Baseball LL - Black",
  "Baseball LL - Green",
  // "Baseball LL - Green (Coach)",
  "Baseball LL - White",
  // "Baseball LL - White (Coach)",
  "Baseball LL - Yellow",
  // "Baseball Little League",
  // "Baseball Little League (Coach)",
  "Baseball Machine Pitch",
  // "Baseball Machine Pitch (Coach)",
  "Baseball Senior (Adult) Baseball",
  "Baseball Senior League",
  "Baseball Women's Baseball",
  "Teeball Tee-Ball 6 to 12",
];
